name: Bug Report
description: Report a defect that affects behavior
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what you expected.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Provide exact steps.
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: Browser, OS, Node version, container/non-container.
    validations:
      required: true
